config/routes.rb
Rails.application.routes.draw do

  get 'report_forms/index'
  get 'report_forms/update'
  match 'sp_bsbs/prompt_report' => 'sp_bsbs#prompt_report', via: [:get, :post]

  get 'log_management/index'
  get 'log_management/search'
  match 'config/init_site', via: [:get, :post]
  get 'site-logo' => 'config#site_logo'

  post 'sms_helper/send_msg'

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  match 'update-account' => 'users#update_account', via: [:get, :post]
  match 'fsnip/sso' => 'ca_helper#fsnip_sso', via: [:get, :post]
  match 'fsnip/logout' => 'ca_helper#fsnip_logout', via: [:get, :post]

  resources :jg_bsb_stamps do
    get 'cover'
  end
    get 'ca_helper/create_text' => 'ca_helper#create_text'
     get  'ca_helper/hash_client_sign' => 'ca_helper#hash_client_sign'
    get 'ca_helper/client_sign_pdf' => 'ca_helper#client_sign_pdf'
  post 'ca_helper/client_sign_pdf'
  get "ca_helper/verify_report"
  post "ca_helper/verify_report"
  resources :ca_helper do
    collection do
      get 'by_ca_info'
      get 'print_pdf'
    end
  end

  get "beica_sso" => 'ca_helper#sso'
	get "synchronize_info" => "ca_helper#account_sync"
  resources :xsbg_tt_data
  resources :xsbg_tts
  resources :sample_members do
    member do
      get 'portrait'
    end
  end

  resources :welcome_notices do
    member do
      get "attachment"
    end
  end

  resources :sp_bsb_publications do
    collection do
      get 'check_duplicate'
      post 'check_duplicate'

      get 'unpublished'
      get 'published'

      post 'publish_bsbs'
      post 'publish_bsbs_from_xls'
    end
    member do
      get 'show_publication'
    end
  end
  post "sp_bsb_publications_filtered" => "sp_bsb_publications#index"

  resources :company_standards do
    member do
      get "attachment"
    end
  end

  # 附件管理
  match "attachment/upload", :via => [:post, :patch]
  get "attachments/:id/download" => "attachment#download"
  get "attachments/:id/preview" => "attachment#preview"
  post "attachments/:id/destroy" => "attachment#destroy"
  delete "destroy_attachment" => "attachment#destroy"
  post 'tinymce_assets' => 'attachment#tinymce_upload'

  resources :baosong_as
  resources :baosong_bs do
    collection do
      get "by_name" => "baosong_bs#baosong_bs_by_name"
      get "by_cityname" => "baosong_bs#baosong_bs_by_cityname"
      get "by_rwly" => "baosong_bs#baosong_bs_by_rwly"
    end

    member do
      get "categories"
    end
  end

  resources :baosong_as_newests
  resources :baosong_bs_newests do
    collection do
      get "by_name" => "baosong_bs_newests#baosong_bs_by_name"
      get "by_cityname" => "baosong_bs_newests#baosong_bs_by_cityname"
      get "categories"
			get "check_items"
    end
  end

  # Category Helper Controller
  post 'category_batch_delete/:category' => 'category_helper#batch_delete'
  post 'create_category/:category' => 'category_helper#create'
  post 'update_category/:category' => 'category_helper#update'
	post  'create_categorys/:category'=> 'category_helper#batch_create'
	get  'query_category/:category'  => 'category_helper#query_categorys'

  resources :a_categories do
    collection do
      get "categories"
    end
  end

  get "a_categories_by_identifier" => "a_categories#by_identifier"
  get "b_categories_by_a_id" => "b_categories#by_id"
  get "c_categories_by_b_id" => "c_categories#by_id"
  get "d_categories_by_c_id" => "d_categories#by_id"

  get "check_items_by_d_id" => "d_categories#check_items"

  # 更新 check items
  post 'd_categories/:id/update_check_items' => 'd_categories#update_check_items'

  resources :sys_provinces
  get 'prov_data' => 'sys_provinces#prov_data'
  get 'new_prov_data' => 'sys_provinces#new_prov_data'
  get 'prov' => 'sys_provinces#prov'
  get 'sub_provs' => 'sys_provinces#sub_provs'
  post 'create_prov' => 'sys_provinces#create_prov'
  post 'update_prov' => 'sys_provinces#update_prov'

  match "tasks/deploy", via: [:get, :post]
  # 省局任务部署
  match "tasks/deploy_prov", via: [:get, :post]

  # 省局部署抽检任务
  post "tasks/create_delegate_plan"

  # 部署各省局抽检任务
  post "tasks/create_prov_plan"

  # 部署局本级任务
  post "tasks/create_direct_plan"

  # 部署局本级抽检任务
  post "tasks/create_top_plan"

  get "tasks/assign"
  get "assign_by_categories_id" => 'tasks#assign_validate'
  match 'tasks/check', via: [:get, :post]

  get "yycz/new"
  get "yycz/dj"
  get "yycz/gzap"
  get "yycz/renew"
  post "yycz/renew"
  get "yycz/cztb"
  get "yycz/czsh"
  get "yycz_from_bsb/:id" => "yycz#from_bsb"
  get "yycz/:id" => "yycz#show"
  get "yycz/:id/download_file" => "yycz#download_file"
  post "yycz_create" => "yycz#create"
  post "yycz/:id" => "yycz#update"
  post "yycz_assign_task" => "yycz#assign_task"
  post "yycz_revert" => "yycz#yycz_revert"
  post "wtyp_czb_revert" => "wtyp_czbs#revert"

  resources :spkj_bsbs

  resources :wtyp_czbs
  post 'wtyp_assign_task' => 'wtyp_czbs#assign_task'
  get 'wtyp_czbs_by_state/:state' => 'wtyp_czbs#index'
  post 'update_wtyp_czbs/:id' => 'wtyp_czbs#update'
  post 'wtyp_czbs/:part_id/duban' => 'wtyp_czbs#duban'
  get 'wtyp_xc_attachment/:id' => 'wtyp_czbs#xc_attachment'
  get 'wtyp_pc_attachment/:id' => 'wtyp_czbs#pc_attachment'
  get 'wtyp_xz_attachment/:id' => 'wtyp_czbs#xz_attachment'
  get 'wtyp_qd_attachment/:id' => 'wtyp_czbs#qd_attachment'

  resources :jg_bsbs do
    member do
      post 'rename'
      #get 'by_rwly'
    end

    collection do
      match 'merge_request', via: [:get, :post]
      get 'by_province'
      get 'by_jg_name'
    end
  end

  post "jg_bsbs_import_data_excel" => "jg_bsbs#import_data_excel"
  resources :jg_bsbs do
    member do
      get "attachment"
    end
  end


  resources :sp_company_infos
  get 'sp_company_infos_list' => 'sp_company_infos#list'
  get 'sp_company_info_by_yyzz' => 'sp_company_infos#by_yyzz'

  resources :sp_production_infos
  get 'sp_production_infos_list' => 'sp_production_infos#list'
  get 'sp_production_company_infos_list' => 'sp_production_infos#company_list'
  get 'sp_production_info_by_scxkz' => 'sp_production_infos#by_scxkz'

  resources :sp_standards
  resources :spdata
  resources :locations

  resources :flexcontents
  post "flexcontents_additem" => 'flexcontents#additem'
  get "flexcontents_additem" => 'flexcontents#additem'

  resources :hzp_bsbs
  post "hzp_bsbs_import_excel" => "hzp_bsbs#import_excel"
  post "hzp_bsbs_export_excel" => "hzp_bsbs#export_excel"
  post "hzp_bsbs_export_info_excel" => "hzp_bsbs#export_info_excel"
  post "hzp_bsbs_spsearch" => 'hzp_bsbs#spsearch'
  get "hzp_bsbs_spsearch" => 'hzp_bsbs#spsearch'
  get "hzp_bsb_submit" => 'hzp_bsbs#submit'
  post "hzp_bsbs_import_hzp_standards" => "hzp_bsbs#import_hzp_standards"
  post "hzp_bsbs_change_data_excel" => "hzp_bsbs#change_data_excel"

  resources :sp_bsbs do
    member do
      get "print"
      post "fail_pdf_report"
      post "remove_fail_report"
      get "fail_pdf_report"
      post "push_base_data"
      get 'xsbg'
      get "cyd"
      get "cyjygzs"
      get "preview_ca_pdf"
      get 'report'
    end
    collection do
     get 'no_available_pdf_found'
     get 'by_ca_info'
     get 'print_pdf'
     get 'super_jg'
     get 'sampling_process'
    end
  end
  resources :pad_sp_bsbs do
    member do
      get "accept_file"
      get "cyd"
      get "cyjygzs"
      get "picture/:sort_index" => "pad_sp_bsbs#picture"
    end
  end

  namespace "api" do
    namespace "v1" do
      post "sp_bsbs/submit/:id" => "sp_bsbs#submit"
      post "sp_bsbs/transfer" => "sp_bsbs#transfer"
      post "sp_bsbs/:id/do_step_:step" => "sp_bsbs#do_step"
      post "sp_bsbs/:id/upload_picture" => "sp_bsbs#upload_picture"
      get "sp_bsbs/:id/picture/:sort_index" => "sp_bsbs#picture"
      get "get_provinces" => "sp_bsbs#get_provinces"
      get "sp_bsbs/index"
      post "sp_bsbs/is_valid"
      get "sp_bsbs/check_sp_production_info"
      get "sp_bsbs/tasks"
      post "sp_bsbs/sync"
      post "users/auth"
      post "users/ca_auth"
			get 'users/ca_get_random'
      post "users/update_location"
			post 'sp_bsbs/:id/ca_sign' => 'sp_bsbs#ca_sign'

			get 'scqy' => 'sp_bsbs#scqy_infos'
			get 'bcydw' => 'sp_bsbs#bcydw_infos'

      get "client/version"
      get "client/download"
      post "hccz/list"
      get "hccz/list"
      get 'hccz/:cjbh/report' => 'hccz#report'
			post "sp_bsbs/sync_sp_bsb"
			post "spdata/sync_spdaum"
			post "spdata/transfer"
    end

    # 我查查
    namespace 'v3' do
      post 'openapi/sample_add_or_edit' => 'openapi#sample_add_or_edit'
      post 'openapi/sampledelete' => 'openapi#delete_sp_bsb'
      get  'user/login'
      #食安云
      post 'interface_user/new_user' => 'interface_user#new_user'
      post 'interface_user/update_user_uuid' => 'interface_user#update_user_uuid'
      post 'interface_jg/handing_jg_bsb' => 'interface_jg#handing_jg_bsb'
      post 'interface_jg/handing_jgbsb_super' => 'interface_jg#handing_jgbsb_super'
      post 'interface_region/new_region' => 'interface_region#new_region'
      post 'interface_stamps/jg_bsb_stamps_sync' => 'interface_stamps#jg_bsb_stamps_sync'
      post 'interface_baosong/baosongs_sync' => 'interface_baosong#baosong_sync'
    end
  end

  post "pad_sp_bsbs_spsearch" => "pad_sp_bsbs#spsearch"
  get "pad_sp_bsbs_spsearch" => "pad_sp_bsbs#spsearch"

  get "checkout_standard" => "sp_bsbs#checkout_standard"
  get "yycz_info_by_cydbh" => "yycz#yycz_info_by_cydbh"
  resources :static_queues
  post "sp_bsbs_import_excel" => "sp_bsbs#import_excel"
  post "sp_bsbs_import_data_excel" => "sp_bsbs#import_data_excel"
  post "sp_bsbs_import_temp_data_excel" => "sp_bsbs#import_temp_data_excel"
  post "sp_bsbs_import_zbydata_excel" => "sp_bsbs#import_zbydata_excel"
  post "sp_bsbs_import_zjydata_excel" => "sp_bsbs#import_zjydata_excel"
  post "sp_bsbs_export_excel" => "sp_bsbs#export_excel"
  post "sp_bsbs_export_data_excel" => "sp_bsbs#export_data_excel"
  post "sp_bsbs_export_excel_search" => "sp_bsbs#export_excel_search"

app/models/xsbg_tt.rb
class XsbgTt < ActiveRecord::Base
  #attr_accessible :CJBH, :GJMC, :sp_bsb_id, :spdata_ids
	attr_accessor :spdata_ids

	validates_uniqueness_of :sp_bsb_id, :message => "已存在该条报告信息"

	after_create :save_data

	private
	def save_data
		Spdatum.where("id IN (?)", self.spdata_ids.split(',').map{|id| id.to_i}).each do |data|
			xsbg_data = XsbgTtDatum.new(spdata_id: data.id, sp_bsb_id: data.sp_bsb_id, xsbg_tt_id: self.id, CJBH: self.CJBH)
			data.attributes.keys.each do |key|
				if !['updated_at', 'created_at', 'id'].include?(key)
					xsbg_data.send("#{key}=", data[key])
				end
			end
			xsbg_data.save
		end
	end
end

app/controllers/xsbg_tts_controller.rb
class XsbgTtsController < ApplicationController
  # GET /xsbg_tts
  # GET /xsbg_tts.json
  def index
    @xsbg_tts = XsbgTt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @xsbg_tts }
    end
  end

  # GET /xsbg_tts/1
  # GET /xsbg_tts/1.json
  def show
    @xsbg_tt = XsbgTt.find(params[:id])

    @sp_bsb = SpBsb.find(@xsbg_tt.sp_bsb_id)

		@xsbg = XsbgTt.find_by_sp_bsb_id(@sp_bsb.id)

    @items = XsbgTtDatum.where(xsbg_tt_id: @xsbg_tt.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @xsbg_tt }
    end
  end

  # GET /xsbg_tts/new
  # GET /xsbg_tts/new.json
  def new
    @xsbg_tt = XsbgTt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @xsbg_tt }
    end
  end

  # GET /xsbg_tts/1/edit
  def edit
    @xsbg_tt = XsbgTt.find(params[:id])
  end

  # POST /xsbg_tts
  # POST /xsbg_tts.json
  def create
    @xsbg_tt = XsbgTt.new(params[:xsbg_tt])

    respond_to do |format|
      if @xsbg_tt.save
        format.html { redirect_to @xsbg_tt, notice: 'Xsbg tt was successfully created.' }
        format.json { render json: @xsbg_tt, status: :created, location: @xsbg_tt }
      else
        format.html { render action: "new" }
        format.json { render json: @xsbg_tt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /xsbg_tts/1
  # PUT /xsbg_tts/1.json
  def update
    @xsbg_tt = XsbgTt.find(params[:id])

    respond_to do |format|
      if @xsbg_tt.update_attributes(params[:xsbg_tt])
        format.html { redirect_to @xsbg_tt, notice: 'Xsbg tt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @xsbg_tt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xsbg_tts/1
  # DELETE /xsbg_tts/1.json
  def destroy
    @xsbg_tt = XsbgTt.find(params[:id])
    @xsbg_tt.destroy

    respond_to do |format|
      format.html { redirect_to xsbg_tts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/xsbg_tts_helper.rb
module XsbgTtsHelper
end

app/views/xsbg_tts/_form.html.erb
<%= form_for(@xsbg_tt) do |f| %>
  <% if @xsbg_tt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xsbg_tt.errors.count, "error") %> prohibited this xsbg_tt from being saved:</h2>

      <ul>
      <% @xsbg_tt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :GJMC %><br />
    <%= f.text_field :GJMC %>
  </div>
  <div class="field">
    <%= f.label :CJBH %><br />
    <%= f.text_field :CJBH %>
  </div>
  <div class="field">
    <%= f.label :sp_bsb_id %><br />
    <%= f.number_field :sp_bsb_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xsbg_tts/edit.html.erb
<h1>Editing xsbg_tt</h1>

<%= render 'form' %>

<%= link_to 'Show', @xsbg_tt %> |
<%= link_to 'Back', xsbg_tts_path %>

app/views/xsbg_tts/index.html.erb
<h1>Listing xsbg_tts</h1>

<table>
  <tr>
    <th>Gjmc</th>
    <th>Cjbh</th>
    <th>Sp bsb</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @xsbg_tts.each do |xsbg_tt| %>
  <tr>
    <td><%= xsbg_tt.GJMC %></td>
    <td><%= xsbg_tt.CJBH %></td>
    <td><%= xsbg_tt.sp_bsb_id %></td>
    <td><%= link_to 'Show', xsbg_tt %></td>
    <td><%= link_to 'Edit', edit_xsbg_tt_path(xsbg_tt) %></td>
    <td><%= link_to 'Destroy', xsbg_tt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Xsbg tt', new_xsbg_tt_path %>

app/views/xsbg_tts/new.html.erb
<h1>New xsbg_tt</h1>

<%= render 'form' %>

<%= link_to 'Back', xsbg_tts_path %>

app/views/xsbg_tts/show.html.erb
<style type="text/css">
@media print {
  .main_left, .banner_sc, .sys-nav, #top, .copyright {
    display: none;
  }
  #mainbox {
  }
  .main_right {
    width: 100% !important;
  }
  .panel {
    border: none;
  }
  th, td {
    border:solid #000 !important;
    border-width:0 1px 1px 0 !important;
    text-align: center;
  }
  table {
    border:solid #000 !important;
    border-width:1px 0 0 1px !important;
  }
}
td {
  word-wrap: break-word;
}

.ctner {
  overflow: scroll;
}
</style>
<h3 class="text-center">食品安全抽样检验限时报告情况表</h3> 
<div class="text-right">（编号：<%= @sp_bsb.sp_s_16 %>）</div> 
<div class="form-inline"><%= @xsbg.GJMC %>食品药品管理局：</div>
<br>
&emsp;&emsp;我单位近期执《2015年国家食品药品监督管理总局食品安全监督抽检和风险监测计划》发现，下表所提及样品检出存在严重健康风险问题。按照该计划有关要求，现将有关情况报告你局。请按照《食品安全监督抽检和风险监测工作规范》调查核实和处理。 
<table data-toggle="table" data-reorderable-columns="true" class="table table-bordered"> 
	<thead>
		<tr> 
			<th>序号</th> 
			<th>样品编号</th> 
			<th>产品名称</th> 
			<th>生产日期</th> 
			<th>规格型号</th> 
			<th>商标</th> 
			<th>生产企业名称</th> 
			<th>生产单位详细地址</th> 
			<th>采样区域</th> 
			<th>采样地点</th> 
			<th>检测项目</th> 
			<th>方法标准</th> 
			<th>检测值</th> 
			<th width="60">标准值(或参考值)</th> 
			<th>判定依据</th> 
			<th>结果说明</th> 
		</tr> 
	</thead>
	<tbody>
		<% @items.each_with_index do |item, index|%>
		<tr> 
			<td><%= index + 1 %></td> 
			<td><%= @sp_bsb.sp_s_16 %></td> 
			<td><%= @sp_bsb.sp_s_14 %></td> 
			<td><%= @sp_bsb.sp_d_28 %></td> 
			<td><%= @sp_bsb.sp_s_26 %></td> 
			<td><%= @sp_bsb.sp_s_74 %></td> 
			<td><%= @sp_bsb.sp_s_64 %></td> 
			<td><%= @sp_bsb.sp_s_65 %></td> 
			<td><%= @sp_bsb.sp_s_68 %></td> 
			<td><%= @sp_bsb.sp_s_68 %></td> 
			<td><%= item.spdata_0 %></td> 
			<td><%= item.spdata_15 %></td> 
			<td><%= item.spdata_1 %></td> 
			<td><%= item.spdata_13 %></td> 
			<td><%= item.spdata_3 %></td> 
			<td><%= item.spdata_17 %></td> 
		</tr>
		<% end %>
	</tbody>
</table> 
<div class="xsbg_text"> 
 <p>检验机构联系人：<%= @sp_bsb.sp_s_49 %>&emsp;&emsp; 联系电话：<%= @sp_bsb.sp_s_50 %></p> 
 <p align="right" style="margin-right:40px">（检验单位公章）<br> <%= Time.now.strftime("%Y年%m月%d日") %></p> 
 <p>抄报：中国食品药品检定研究院（秘书处）、总局稽查局。</p> 
</div>
<hr>