config/routes.rb
Rails.application.routes.draw do

  get 'report_forms/index'
  get 'report_forms/update'
  match 'sp_bsbs/prompt_report' => 'sp_bsbs#prompt_report', via: [:get, :post]

  get 'log_management/index'
  get 'log_management/search'
  match 'config/init_site', via: [:get, :post]
  get 'site-logo' => 'config#site_logo'

  post 'sms_helper/send_msg'

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  match 'update-account' => 'users#update_account', via: [:get, :post]
  match 'fsnip/sso' => 'ca_helper#fsnip_sso', via: [:get, :post]
  match 'fsnip/logout' => 'ca_helper#fsnip_logout', via: [:get, :post]

  resources :jg_bsb_stamps do
    get 'cover'
  end
    get 'ca_helper/create_text' => 'ca_helper#create_text'
     get  'ca_helper/hash_client_sign' => 'ca_helper#hash_client_sign'
    get 'ca_helper/client_sign_pdf' => 'ca_helper#client_sign_pdf'
  post 'ca_helper/client_sign_pdf'
  get "ca_helper/verify_report"
  post "ca_helper/verify_report"
  resources :ca_helper do
    collection do
      get 'by_ca_info'
      get 'print_pdf'
    end
  end

  get "beica_sso" => 'ca_helper#sso'
	get "synchronize_info" => "ca_helper#account_sync"
  resources :xsbg_tt_data
  resources :xsbg_tts
  resources :sample_members do
    member do
      get 'portrait'
    end
  end

  resources :welcome_notices do
    member do
      get "attachment"
    end
  end

  resources :sp_bsb_publications do
    collection do
      get 'check_duplicate'
      post 'check_duplicate'

      get 'unpublished'
      get 'published'

      post 'publish_bsbs'
      post 'publish_bsbs_from_xls'
    end
    member do
      get 'show_publication'
    end
  end
  post "sp_bsb_publications_filtered" => "sp_bsb_publications#index"

  resources :company_standards do
    member do
      get "attachment"
    end
  end

  # 附件管理
  match "attachment/upload", :via => [:post, :patch]
  get "attachments/:id/download" => "attachment#download"
  get "attachments/:id/preview" => "attachment#preview"
  post "attachments/:id/destroy" => "attachment#destroy"
  delete "destroy_attachment" => "attachment#destroy"
  post 'tinymce_assets' => 'attachment#tinymce_upload'

  resources :baosong_as
  resources :baosong_bs do
    collection do
      get "by_name" => "baosong_bs#baosong_bs_by_name"
      get "by_cityname" => "baosong_bs#baosong_bs_by_cityname"
      get "by_rwly" => "baosong_bs#baosong_bs_by_rwly"
    end

    member do
      get "categories"
    end
  end

  resources :baosong_as_newests
  resources :baosong_bs_newests do
    collection do
      get "by_name" => "baosong_bs_newests#baosong_bs_by_name"
      get "by_cityname" => "baosong_bs_newests#baosong_bs_by_cityname"
      get "categories"
			get "check_items"
    end
  end

  # Category Helper Controller
  post 'category_batch_delete/:category' => 'category_helper#batch_delete'
  post 'create_category/:category' => 'category_helper#create'
  post 'update_category/:category' => 'category_helper#update'
	post  'create_categorys/:category'=> 'category_helper#batch_create'
	get  'query_category/:category'  => 'category_helper#query_categorys'

  resources :a_categories do
    collection do
      get "categories"
    end
  end

  get "a_categories_by_identifier" => "a_categories#by_identifier"
  get "b_categories_by_a_id" => "b_categories#by_id"
  get "c_categories_by_b_id" => "c_categories#by_id"
  get "d_categories_by_c_id" => "d_categories#by_id"

  get "check_items_by_d_id" => "d_categories#check_items"

  # 更新 check items
  post 'd_categories/:id/update_check_items' => 'd_categories#update_check_items'

  resources :sys_provinces
  get 'prov_data' => 'sys_provinces#prov_data'
  get 'new_prov_data' => 'sys_provinces#new_prov_data'
  get 'prov' => 'sys_provinces#prov'
  get 'sub_provs' => 'sys_provinces#sub_provs'
  post 'create_prov' => 'sys_provinces#create_prov'
  post 'update_prov' => 'sys_provinces#update_prov'

  match "tasks/deploy", via: [:get, :post]
  # 省局任务部署
  match "tasks/deploy_prov", via: [:get, :post]

  # 省局部署抽检任务
  post "tasks/create_delegate_plan"

  # 部署各省局抽检任务
  post "tasks/create_prov_plan"

  # 部署局本级任务
  post "tasks/create_direct_plan"

  # 部署局本级抽检任务
  post "tasks/create_top_plan"

  get "tasks/assign"
  get "assign_by_categories_id" => 'tasks#assign_validate'
  match 'tasks/check', via: [:get, :post]

  get "yycz/new"
  get "yycz/dj"
  get "yycz/gzap"
  get "yycz/renew"
  post "yycz/renew"
  get "yycz/cztb"
  get "yycz/czsh"
  get "yycz_from_bsb/:id" => "yycz#from_bsb"
  get "yycz/:id" => "yycz#show"
  get "yycz/:id/download_file" => "yycz#download_file"
  post "yycz_create" => "yycz#create"
  post "yycz/:id" => "yycz#update"
  post "yycz_assign_task" => "yycz#assign_task"
  post "yycz_revert" => "yycz#yycz_revert"
  post "wtyp_czb_revert" => "wtyp_czbs#revert"

  resources :spkj_bsbs

  resources :wtyp_czbs
  post 'wtyp_assign_task' => 'wtyp_czbs#assign_task'
  get 'wtyp_czbs_by_state/:state' => 'wtyp_czbs#index'
  post 'update_wtyp_czbs/:id' => 'wtyp_czbs#update'
  post 'wtyp_czbs/:part_id/duban' => 'wtyp_czbs#duban'
  get 'wtyp_xc_attachment/:id' => 'wtyp_czbs#xc_attachment'
  get 'wtyp_pc_attachment/:id' => 'wtyp_czbs#pc_attachment'
  get 'wtyp_xz_attachment/:id' => 'wtyp_czbs#xz_attachment'
  get 'wtyp_qd_attachment/:id' => 'wtyp_czbs#qd_attachment'

  resources :jg_bsbs do
    member do
      post 'rename'
      #get 'by_rwly'
    end

    collection do
      match 'merge_request', via: [:get, :post]
      get 'by_province'
      get 'by_jg_name'
    end
  end

  post "jg_bsbs_import_data_excel" => "jg_bsbs#import_data_excel"
  resources :jg_bsbs do
    member do
      get "attachment"
    end
  end


  resources :sp_company_infos
  get 'sp_company_infos_list' => 'sp_company_infos#list'
  get 'sp_company_info_by_yyzz' => 'sp_company_infos#by_yyzz'

  resources :sp_production_infos
  get 'sp_production_infos_list' => 'sp_production_infos#list'
  get 'sp_production_company_infos_list' => 'sp_production_infos#company_list'
  get 'sp_production_info_by_scxkz' => 'sp_production_infos#by_scxkz'

  resources :sp_standards
  resources :spdata
  resources :locations

  resources :flexcontents
  post "flexcontents_additem" => 'flexcontents#additem'
  get "flexcontents_additem" => 'flexcontents#additem'

  resources :hzp_bsbs
  post "hzp_bsbs_import_excel" => "hzp_bsbs#import_excel"
  post "hzp_bsbs_export_excel" => "hzp_bsbs#export_excel"
  post "hzp_bsbs_export_info_excel" => "hzp_bsbs#export_info_excel"
  post "hzp_bsbs_spsearch" => 'hzp_bsbs#spsearch'
  get "hzp_bsbs_spsearch" => 'hzp_bsbs#spsearch'
  get "hzp_bsb_submit" => 'hzp_bsbs#submit'
  post "hzp_bsbs_import_hzp_standards" => "hzp_bsbs#import_hzp_standards"
  post "hzp_bsbs_change_data_excel" => "hzp_bsbs#change_data_excel"

  resources :sp_bsbs do
    member do
      get "print"
      post "fail_pdf_report"
      post "remove_fail_report"
      get "fail_pdf_report"
      post "push_base_data"
      get 'xsbg'
      get "cyd"
      get "cyjygzs"
      get "preview_ca_pdf"
      get 'report'
    end
    collection do
     get 'no_available_pdf_found'
     get 'by_ca_info'
     get 'print_pdf'
     get 'super_jg'
     get 'sampling_process'
    end
  end
  resources :pad_sp_bsbs do
    member do
      get "accept_file"
      get "cyd"
      get "cyjygzs"
      get "picture/:sort_index" => "pad_sp_bsbs#picture"
    end
  end

  namespace "api" do
    namespace "v1" do
      post "sp_bsbs/submit/:id" => "sp_bsbs#submit"
      post "sp_bsbs/transfer" => "sp_bsbs#transfer"
      post "sp_bsbs/:id/do_step_:step" => "sp_bsbs#do_step"
      post "sp_bsbs/:id/upload_picture" => "sp_bsbs#upload_picture"
      get "sp_bsbs/:id/picture/:sort_index" => "sp_bsbs#picture"
      get "get_provinces" => "sp_bsbs#get_provinces"
      get "sp_bsbs/index"
      post "sp_bsbs/is_valid"
      get "sp_bsbs/check_sp_production_info"
      get "sp_bsbs/tasks"
      post "sp_bsbs/sync"
      post "users/auth"
      post "users/ca_auth"
			get 'users/ca_get_random'
      post "users/update_location"
			post 'sp_bsbs/:id/ca_sign' => 'sp_bsbs#ca_sign'

			get 'scqy' => 'sp_bsbs#scqy_infos'
			get 'bcydw' => 'sp_bsbs#bcydw_infos'

      get "client/version"
      get "client/download"
      post "hccz/list"
      get "hccz/list"
      get 'hccz/:cjbh/report' => 'hccz#report'
			post "sp_bsbs/sync_sp_bsb"
			post "spdata/sync_spdaum"
			post "spdata/transfer"
    end

    # 我查查
    namespace 'v3' do
      post 'openapi/sample_add_or_edit' => 'openapi#sample_add_or_edit'
      post 'openapi/sampledelete' => 'openapi#delete_sp_bsb'
      get  'user/login'
      #食安云
      post 'interface_user/new_user' => 'interface_user#new_user'
      post 'interface_user/update_user_uuid' => 'interface_user#update_user_uuid'
      post 'interface_jg/handing_jg_bsb' => 'interface_jg#handing_jg_bsb'
      post 'interface_jg/handing_jgbsb_super' => 'interface_jg#handing_jgbsb_super'
      post 'interface_region/new_region' => 'interface_region#new_region'
      post 'interface_stamps/jg_bsb_stamps_sync' => 'interface_stamps#jg_bsb_stamps_sync'
      post 'interface_baosong/baosongs_sync' => 'interface_baosong#baosong_sync'
    end
  end

  post "pad_sp_bsbs_spsearch" => "pad_sp_bsbs#spsearch"
  get "pad_sp_bsbs_spsearch" => "pad_sp_bsbs#spsearch"

  get "checkout_standard" => "sp_bsbs#checkout_standard"
  get "yycz_info_by_cydbh" => "yycz#yycz_info_by_cydbh"
  resources :static_queues
  post "sp_bsbs_import_excel" => "sp_bsbs#import_excel"
  post "sp_bsbs_import_data_excel" => "sp_bsbs#import_data_excel"
  post "sp_bsbs_import_temp_data_excel" => "sp_bsbs#import_temp_data_excel"
  post "sp_bsbs_import_zbydata_excel" => "sp_bsbs#import_zbydata_excel"
  post "sp_bsbs_import_zjydata_excel" => "sp_bsbs#import_zjydata_excel"
  post "sp_bsbs_export_excel" => "sp_bsbs#export_excel"
  post "sp_bsbs_export_data_excel" => "sp_bsbs#export_data_excel"
  post "sp_bsbs_export_excel_search" => "sp_bsbs#export_excel_search"

app/models/sp_production_info.rb
class SpProductionInfo < ActiveRecord::Base
  # attr_accessible :cpmc, :fzdw, :fzrq, :jyfs, :qymc, :scbh, :scdz, :zs, :zsyxq, :sp_s_3, :sp_s_4, :sp_s_5, :spdl,:spyl,:spcyl,:spxl
end

app/controllers/sp_production_infos_controller.rb
#encoding: utf-8
class SpProductionInfosController < ApplicationController
  def index
    @sp_production_infos = SpProductionInfo.paginate(:page => params[:page], :per_page => 50)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sp_production_infos }
    end
  end
  
  def new
    @sp_production_info = SpProductionInfo.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sp_production_info }
    end
  end
  
  # GET /sp_production_infos/1/edit
  def edit
    @sp_production_info = SpProductionInfo.find(params[:id])
  end
  
  # POST /sp_production_infos
  # POST /sp_production_infos.json
  def create
    @sp_production_info = SpProductionInfo.new(sp_production_info_params)
    
    respond_to do |format|
      if @sp_production_info.save
        format.html { redirect_to "/sp_production_infos" }
        format.json { render json: @sp_production_info, status: :created, location: @sp_production_info }
      else
        format.html { render action: "new" }
        format.json { render json: @sp_production_info.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /sp_production_infos/1
  # PUT /sp_production_infos/1.json
  def update
    @sp_production_info = SpProductionInfo.find(params[:id])
    
    respond_to do |format|
      if @sp_production_info.update_attributes(sp_production_info_params)
        format.html { redirect_to "/sp_production_infos" }
        format.json { head :no_content }
        else
        format.html { render action: "edit" }
        format.json { render json: @sp_production_info.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /sp_production_infos/1
  # DELETE /sp_production_infos/1.json
  def destroy
    @sp_production_info = SpProductionInfo.find(params[:id])
    @sp_production_info.destroy
    
    respond_to do |format|
      format.html { redirect_to sp_production_infos_url }
      format.json { head :no_content }
    end
  end

	def by_scxkz
		unless params[:scxkz].blank?
			@product = SpProductionInfo.find_by_scbh(params[:scxkz])
			if @product.nil?
				render :json => {status: 'ERR', msg: "未找到相应信息"}
			else
				render :json => {status: 'OK', msg: @product}
			end
		else
			render :json => {status: 'ERR', msg: "请提供参数scxkz"}
		end
	end

  def list
    respond_to do |format|
      if params[:qymc].blank?
        format.json { render :json => { :status => 'ERR', :msg => nil} }
      else
        @products = SpProductionInfo.select('id, cpmc, scbh').where(qymc: params[:qymc])
        format.json { render :json => { :status => 'OK', :msg => nil, :products => @products.map{|record| {:id => record.id, :title => "#{record.scbh}/#{record.cpmc}"}}} }
      end
    end
  end

  def company_list
    respond_to do |format|
      if params[:condition].blank?
        format.json { render :json => { :status => 'ERR', :msg => nil} }
      else
        @products = SpProductionInfo.select('id, cpmc, scbh, qymc').where(params[:condition])
        format.json { render :json => { :status => 'OK', :msg => nil, :products => @products.map{|record| {id: record.id, qymc: record.qymc, title:  "#{record.scbh}/#{record.cpmc}"}}} }
      end
    end
  end

	private
	def sp_production_info_params
		params.require(:sp_production_info).permit(:sp_proid,:cpmc, :fzdw, :fzrq, :jyfs, :qymc, :scbh, :scdz, :zs, :zsyxq, :sp_s_3, :sp_s_4, :sp_s_5, :spdl,:spyl,:spcyl,:spxl)
	end
end

app/views/sp_production_infos/_form.html.erb
<%= javascript_include_tag 'spdata1' %>
<%= javascript_include_tag 'spdata2' %>
<%= javascript_include_tag 'spdata3' %>
<%= javascript_include_tag 'spdata4' %>
<%= javascript_include_tag 'spdata5' %>
<%= javascript_include_tag 'spdata6' %>
<%= javascript_include_tag 'spdata7' %>
<%= javascript_include_tag 'spdata8' %>
<%= javascript_include_tag 'spdata10' %>

<style type="text/css">

  .style1 {
    border-collapse: collapse;
    font-size: 9pt;
    font-family: Calibri, sans-serif;
    border-style: none;
    border-color: inherit;
    border-width: medium;
    table-layout: fixed;
  }

  .style1 td {
    border: solid windowtext 1.0px;
    padding: 0cm 5.4pt 0cm 5.4pt;
    height: 30px;
  }

  .style1 th {
    border: solid windowtext 1.0px;
    padding: 0cm 5.4pt 0cm 5.4pt;
    height: 30px;
  }

  .inputText {
    font-size: 12px;
    border-right-width: 0px;
    border-left-width: 0px;
    border-top-width: 0px;
    border-bottom: 1px solid;
    background-color: transparent;

  }

  .height600 {
    height: 600px;
    width: 3000px;
    overflow-y: auto;
    overflow-x: auto;
  }
</style>

<script type="text/javascript">
  $(function () {
    $(".region").CfdaProvince({
      level1: "<%= @sp_production_info.sp_s_3 %>",
      level2: "<%= @sp_production_info.sp_s_4 %>",
      level3: "<%= @sp_production_info.sp_s_5 %>"
    });
    $('#province, #city, #lcity').change(function () {
      $('#sp_production_info_sp_s_3').val($('#province').val());
      $('#sp_production_info_sp_s_4').val($('#city').val());
      $('#sp_production_info_sp_s_5').val($('#lcity').val());
    });

    $.each(SPDL1, function (index, data) {
      $("#sp_production_info_spdl").append("<option value='" + data + "'>" + data + "</option>");
    });

    <% unless @sp_production_info.spdl.blank? %>
    $("#sp_production_info_spdl").val('<%=@sp_production_info.spdl%>');
    index0 = $('#sp_production_info_spdl option').index($('#sp_production_info_spdl option:selected'));
    $.each(SPYL1[index0], function (index, data) {
      $("#sp_production_info_spyl").append("<option value='" + data + "'>" + data + "</option>");
    });
    $("#sp_production_info_spyl").val('<%=@sp_production_info.spyl%>');

    index1 = $('#sp_production_info_spyl option').index($('#sp_production_info_spyl option:selected'));
    $.each(SPCYL1[index0][index1], function (index, data) {
      $("#sp_production_info_spcyl").append("<option value='" + data + "'>" + data + "</option>");
    });
    $("#sp_production_info_spcyl").val('<%=@sp_production_info.spcyl%>');
    index2 = $('#sp_production_info_spcyl option').index($('#sp_production_info_spcyl option:selected'));

    $.each(SPXL1[index0][index1][index2], function (index, data) {
      $("#sp_production_info_spxl").append("<option value='" + data + "'>" + data + "</option>");
    });
    $("#sp_production_info_spxl").val('<%=@sp_production_info.spxl%>');
    <% else %>
    $.each(SPYL1[0], function (index, data) {
      $("#sp_production_info_spyl").append("<option value='" + data + "'>" + data + "</option>");
    });
    $.each(SPCYL1[0][0], function (index, data) {
      $("#sp_production_info_spcyl").append("<option value='" + data + "'>" + data + "</option>");
    });
    $.each(SPXL1[0][0][0], function (index, data) {
      $("#sp_production_info_spxl").append("<option value='" + data + "'>" + data + "</option>");
    });
    index0 = index1 = index2 = index3 = 0;
    <% end%>


    index0 = index1 = index2 = index3 = 0;
    index0 = $('#sp_production_info_spdl option').index($('#sp_production_info_spdl option:selected'));
    index1 = $('#sp_production_info_spyl option').index($('#sp_production_info_spyl option:selected'));
    index2 = $('#sp_production_info_spcyl option').index($('#sp_production_info_spcyl option:selected'));
    index3 = $('#sp_production_info_spxl option').index($('#sp_production_info_spxl option:selected'));

    $("#sp_production_info_spdl").change(function () {
      $("#sp_production_info_spyl").get(0).options.length = 0;
      index0 = this.selectedIndex;
      index1 = 0;
      index2 = 0;
      index3 = 0;

      $.each(SPYL1[index0], function (index, data) {
        $("#sp_production_info_spyl").append("<option value='" + data + "'>" + data + "</option>");
      });
      $("#sp_production_info_spcyl").get(0).options.length = 0;
      $.each(SPCYL1[index0][0], function (index, data) {
        $("#sp_production_info_spcyl").append("<option value='" + data + "'>" + data + "</option>");
      });
      $("#sp_production_info_spxl").get(0).options.length = 0;
      $.each(SPXL1[index0][0][0], function (index, data) {
        $("#sp_production_info_spxl").append("<option value='" + data + "'>" + data + "</option>");
      });

      return;
    });

    $("#sp_production_info_spyl").change(function () {
      $("#sp_production_info_spcyl").get(0).options.length = 0;

      index2 = 0;
      index3 = 0;
      index1 = this.selectedIndex;
      $.each(SPCYL1[index0][index1], function (index, data) {
        $("#sp_production_info_spcyl").append("<option value='" + data + "'>" + data + "</option>");
      });
      $("#sp_production_info_spxl").get(0).options.length = 0;
      $.each(SPXL1[index0][index1][0], function (index, data) {
        $("#sp_production_info_spxl").append("<option value='" + data + "'>" + data + "</option>");
      });
    });

    $("#sp_production_info_spcyl").change(function () {
      $("#sp_production_info_spxl").get(0).options.length = 0;
      index3 = 0;
      index2 = this.selectedIndex;
      $.each(SPXL1[index0][index1][index2], function (index, data) {
        $("#sp_production_info_spxl").append("<option value='" + data + "'>" + data + "</option>");
      });
    });
    $("#sp_production_info_spxl").change(function () {
      index3 = $('#sp_production_info_spxl option').index($('#sp_production_info_spxl option:selected'));
    });
    $('#sp_production_info_spxl').trigger('change');
  });
</script>
<%= form_for(@sp_production_info) do |f| %>
    <% if @sp_production_info.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@sp_production_info.errors.count, "error") %> prohibited this sp_production_info from being
            saved:</h2>
          <ul>
            <% @sp_production_info.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table border="1" cellspacing="0" cellpadding="0" width="820px" class="style1">
      <tr>
        <td colspan="4"><p>生产许可证编号</p></td>
        <td colspan="8"><%= f.text_field :scbh, :class=>"inputText",:style=>"width: 180px; height: 19px" %></td>
        <td colspan="4"><p>产品名称</p></td>
        <td colspan="14"><%= f.text_field :cpmc, :class=>"inputText",:style=>"width: 350px; height: 19px" %></td>
      </tr>
      <tr>
        <td colspan="4" style="width: 73px"><p>生产单位名称</p></td>
        <td colspan="8"><%= f.text_field :qymc, :class => "inputText", :style => "width: 180px; height: 19px" %></td>
        <td colspan="4"><p style="width:73px">生产单位地址</p></td>
        <td colspan="14"><%= f.text_field :scdz, :class=>"inputText",:style=>"width: 350px; height: 19px" %></td>
      </tr>
      <tr>
        <td colspan="4" style="width: 73px"><p>发证单位</p></td>
        <td colspan="8"><%= f.text_field :fzdw, :class => "inputText", :style => "width: 180px; height: 19px" %></td>
        <td colspan="4"><p style="width:73px">发证日期</p></td>
        <td colspan="14"><%= f.text_field :fzrq, :class=>"inputText",:style=>"width: 350px; height: 19px" %></td>
      </tr>
      <tr>
        <td colspan="3" style="width: 73px"><p>所在地区*</p></td>
        <td colspan="27" class="region">
       <!-- <span>
          <select id='province' name='province' class="NoPrint"></select>
          <%#= f.text_field :sp_s_3, :class => "inputText", :style => "width: 60px; height: 19px" %>省(市、自治区)
          <select id='city' name='city'></select>
          <%#= f.text_field :sp_s_4, :class => "inputText", :style => "width: 60px; height: 19px" %>地区(市、州、盟)
          <select id='lcity' name='lcity'></select>
          <%#= f.text_field :sp_s_5, :class => "inputText", :style => "width: 60px; height: 19px" %>县(市、区)
        </span>-->
          <%= f.select :sp_s_3, {}, class: 'form-control input-sm' %>
          <%= f.select :sp_s_4, {}, class: 'form-control input-sm' %>
          <%= f.select :sp_s_5, {}, class: 'form-control input-sm' %>
        </td>
      </tr>
      <tr>
        <td colspan="3" style="width: 73px"><p>样品分类*</p></td>
        <td colspan="27">
          食品大类<%= f.select :spdl, '', {}, {:style => "width: 120px;"} %>
          食品亚类<%= f.select :spyl, '', {}, {:style => "width: 120px;"} %>
          食品次亚类<%= f.select :spcyl, '', {}, {:style => "width: 120px;"} %>
          食品细类<%= f.select :spxl, '', {}, {:style => "width: 120px;"} %>
        </td>
      </tr>
    </table>
    <br/>
    <div class="actions">
      <%= f.submit("保存", :class => 'btn btn-sm btn-success') %>
      <%= link_to '返回', sp_production_infos_path, :class => 'btn btn-info btn-sm' %>
    </div>
<% end %>

app/views/sp_production_infos/edit.html.erb
<div class="page-header">
  <h1>编辑信息</h1>
</div>
<%= render 'form' %>

app/views/sp_production_infos/index.html.erb
<h1>生产企业库列表</h1>

<table class="table table-bordered table-condensed">
  <tr>
    <th>生产许可证编号</th>
    <th>产品名</th>
    <th>发证单位</th>
    <th>企业名称</th>
    <th>所在省</th>
    <th>所在市</th>
    <th>所在县</th>
    <th></th>
    <th></th>
  </tr>

<% @sp_production_infos.each do |sp_production_info| %>
  <tr>
    <td><%= sp_production_info.scbh %></td>
    <td><%= sp_production_info.cpmc %></td>
    <td><%= sp_production_info.fzdw %></td>
    <td><%= sp_production_info.qymc %></td>
    <td><%= sp_production_info.sp_s_3 %></td>
    <td><%= sp_production_info.sp_s_4 %></td>
    <td><%= sp_production_info.sp_s_5 %></td>
    <td><%= link_to '编辑', edit_sp_production_info_path(sp_production_info), :class => 'btn btn-info btn-xs' %></td>
    <td><%= link_to '删除', sp_production_info, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<p><%=will_paginate @sp_production_infos,:params=>params,:separator=>',',:previous_label=>'上一页',:next_label=>'下一页'%></p>
<br />

<%= link_to '新建', new_sp_production_info_path, class: 'btn btn-sm btn-primary' %>

app/views/sp_production_infos/new.html.erb
<h1>新建被抽样产品信息</h1>

<%= render 'form' %>